import type { PriorityTier } from './types';

export const StandardEvents = {
  SLEEP_LOGGED: 'log.sleep.created',
  PRAYER_LOGGED: 'log.prayer.updated',
  WORKOUT_LOGGED: 'log.workout.created',
  MEAL_LOGGED: 'log.meal.created',
  WATER_LOGGED: 'log.water.created',
  MOOD_UPDATED: 'log.mood.updated',
  JOURNAL_SAVED: 'log.journal.saved',
  GOAL_COMPLETED: 'goal.completed',
  ROUTINE_COMPLETED: 'routine.completed',
  URGE_LOGGED: 'recovery.urge.logged',
  RECOVERY_SCORE_UPDATED: 'score.recovery.updated',
  PREDICTION_UPDATED: 'ai.prediction.updated',
  SCHEDULE_OPTIMIZED: 'ai.schedule.optimized',
  AI_RECOMMENDATION_ACCEPTED: 'ai.rec.accepted',
  AI_RECOMMENDATION_DISMISSED: 'ai.rec.dismissed',
  NOTIFICATION_TRIGGERED: 'notification.triggered',
  BACKUP_COMPLETED: 'system.backup.completed',
  DAY_CHANGED: 'system.day.changed',
  PLAN_GENERATED: 'planning.plan.generated',
  PLAN_PROPOSED: 'planning.plan.proposed',
  PLAN_APPROVED: 'planning.plan.approved',
  PLAN_REJECTED: 'planning.plan.rejected',
  PLAN_RESCHEDULED: 'planning.plan.rescheduled',
  PLAN_FAILED: 'planning.plan.failed',
  DECISION_EVALUATED: 'ai.decision.evaluated'
} as const;

export const EventPriorityMap: Record<string, PriorityTier> = {
  [StandardEvents.URGE_LOGGED]: 'P0',
  [StandardEvents.NOTIFICATION_TRIGGERED]: 'P0',
  [StandardEvents.PLAN_FAILED]: 'P0',
  [StandardEvents.DAY_CHANGED]: 'P1',
  [StandardEvents.SLEEP_LOGGED]: 'P1',
  [StandardEvents.PRAYER_LOGGED]: 'P1',
  [StandardEvents.WORKOUT_LOGGED]: 'P1',
  [StandardEvents.GOAL_COMPLETED]: 'P1',
  [StandardEvents.ROUTINE_COMPLETED]: 'P1',
  [StandardEvents.RECOVERY_SCORE_UPDATED]: 'P1',
  [StandardEvents.SCHEDULE_OPTIMIZED]: 'P1',
  [StandardEvents.AI_RECOMMENDATION_ACCEPTED]: 'P1',
  [StandardEvents.PLAN_GENERATED]: 'P1',
  [StandardEvents.PLAN_PROPOSED]: 'P1',
  [StandardEvents.PLAN_APPROVED]: 'P1',
  [StandardEvents.PLAN_RESCHEDULED]: 'P1',
  [StandardEvents.DECISION_EVALUATED]: 'P1',
  [StandardEvents.MEAL_LOGGED]: 'P2',
  [StandardEvents.WATER_LOGGED]: 'P2',
  [StandardEvents.MOOD_UPDATED]: 'P2',
  [StandardEvents.JOURNAL_SAVED]: 'P2',
  [StandardEvents.PREDICTION_UPDATED]: 'P2',
  [StandardEvents.AI_RECOMMENDATION_DISMISSED]: 'P2',
  [StandardEvents.PLAN_REJECTED]: 'P2',
  [StandardEvents.BACKUP_COMPLETED]: 'P3'
};
